# Generated by Django 5.2.4 on 2025-08-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
