# Generated by Django 6.0.2 on 2026-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
